services:
  v2ray:
    image: chinayin/v2ray:5.48.0
    container_name: v2ray
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1081:1081"
    volumes:
      - ./files/config.json:/etc/v2ray/config.json
