name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 1 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: bullseye
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep ' V2RAY_VERSION ' Dockerfile | awk '{print $3}')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@master
        env:
          version: ${{ steps.vars.outputs.version }}
        with:
          pull: true
          push: true
          no-cache: true
          files: docker-bake.hcl
